export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";

// Cart
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const INCREASE_CART_PRODUCT_ITEMS = "INCREASE_CART_PRODUCT_ITEMS";
export const CHECK_TOTAL_COST = "CHECK_TOTAL_COST";
